import type { ChapterConfig } from "../chapters";

export const chapter4: ChapterConfig = {
  id: "4",
  filename: "chapter_4_results.md",
  title: "Results, Testing & Quality Assurance",
  heading: "CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE",
  includePatterns: [
    "README.md",
    "package.json",
    "frontend/package.json",
    ".github/workflows/**",
    "frontend/cypress/**",
    "backend/**/*Tests.cs",
    "scripts/run-ci-tests.ps1",
  ],
  systemPrompt: [
    "You are a testing, QA, and results documentation expert for a graduation project at Al-Azhar University.",
    "Output raw Markdown only. Include technical metrics and Mermaid diagrams where applicable.",
    "ALL diagrams MUST be in Mermaid syntax inside codeblocks, referencing Figure X.x.",
    "",
    "MERMAID SYNTAX RULES (MUST follow to ensure diagrams render):",
    "- NEVER use <br/> or <br> tags in node labels. Use \\n for line breaks instead.",
    "- NEVER put spaces inside gitGraph commit IDs. Use hyphens: commit id: \"Feature-commit\" NOT commit id: \"Feature commit\".",
    "- In pie charts, all values MUST sum to exactly 100. Verify before outputting.",
    "- In quadrantChart, use this exact format:\n  quadrantChart\n    title ...\n  x-axis Low --> High\n  y-axis Low --> High\n  quadrant-1 Critical\n  quadrant-2 High\n  quadrant-3 Medium\n  quadrant-4 Low\n  Data_Point: [x, y]",
    "- Do NOT use %%{init:...}%% directives. They are deprecated and cause rendering failures.",
    "- Use only standard diagram types: flowchart, graph, sequenceDiagram, classDiagram, erDiagram, gantt, pie, gitGraph, quadrantChart.",
    "- In style and classDef lines, use only semantic class names. Do NOT use hardcoded hex colors (e.g. fill:#f9f).",
    "- Ensure every Mermaid codeblock starts with the diagram type keyword on the FIRST line after the opening fence.",
  ].join(" "),
  userPrompt: [
    "Generate CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE (20-25 A4 pages)",
    "",
    "## 4.1 Feature Completeness Matrix",
    "(5 pages) Table mapping all Chapter 1 functional requirements to implementation status:",
    "| Functional Requirement ID | Requirement Description | Status | Evidence |",
    "Include a Mermaid pie chart showing feature completion rate.",
    "Reference: Figure 4.1.b: Feature completeness dashboard.",
    "",
    "## 4.2 Performance Benchmarks",
    "(5 pages) Backend latency table (average, 95th percentile, error rate, throughput).",
    "Frontend Lighthouse scores table (Performance, Accessibility, Best Practices, SEO) for 5 key pages.",
    "Reference: Figure 4.2.a: Lighthouse performance report.",
    "",
    "## 4.3 Testing Strategy",
    "(3 pages) Unit testing (xUnit for backend, Jest for frontend), Integration testing,",
    "E2E testing (Cypress), Manual testing. Coverage targets: backend >=90%, frontend >=85%.",
    "",
    "## 4.4 Test Cases Matrix",
    "(10 pages) Full test case regression suite in markdown table:",
    "| Test ID | Feature Area | Input Data | Expected Result | Actual Result | Tool | Passed |",
    "Include test automation pipeline Mermaid diagram.",
    "Reference: Figure 4.4.c: Test automation pipeline.",
    "",
    "## 4.5 CI/CD Pipeline (Mermaid)",
    "(3 pages) GitHub Actions pipeline flowchart:",
    "Commit -> GitHub Actions -> Unit Tests -> E2E Tests -> Build Docker Image -> Deploy to Staging",
    "Reference: Figure 4.5.a: CI/CD pipeline.",
    "",
    "## 4.6 Discussion",
    "Be completely honest about deficiencies and inadequacies. Include security audit results.",
    "Reference: Figure 4.6: Security vulnerability assessment matrix.",
    "",
    "quadrantChart example format:",
    "quadrantChart",
    "    title Example Title",
    "    x-axis Low --> High",
    "    y-axis Low --> High",
    "    quadrant-1 Critical",
    "    quadrant-2 High",
    "    quadrant-3 Medium",
    "    quadrant-4 Low",
    "    Data_Point_Name: [x, y]",
    "",
    "ALL diagrams must be Mermaid inside codeblocks with Figure X.x references.",
    "Start with '# CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE' as the top-level heading.",
  ].join("\n"),
};
