import type { ChapterConfig } from "../chapters";

export const chapter6: ChapterConfig = {
  id: "6",
  filename: "chapter_6_testing.md",
  title: "Testing & Quality Assurance",
  heading: "CHAPTER 6: TESTING & QUALITY ASSURANCE",
  includePatterns: [
    ".github/workflows/**",
    "frontend/cypress/**",
    "backend/**/*Tests.cs",
    "scripts/run-ci-tests.ps1",
  ],
  systemPrompt: [
    "You are a testing and QA professional writing CHAPTER 6 of an academic graduation project",
    "at Al-Azhar University. Output raw Markdown only.",
    "ALL diagrams MUST be in Mermaid syntax inside codeblocks, referencing Figure X.x.",
    "",
    "MERMAID SYNTAX RULES (MUST follow to ensure diagrams render):",
    "- NEVER use <br/> or <br> tags in node labels. Use \\n for line breaks instead.",
    "- NEVER put spaces inside gitGraph commit IDs. Use hyphens: commit id: \"Feature-commit\" NOT commit id: \"Feature commit\".",
    "- In pie charts, all values MUST sum to exactly 100. Verify before outputting.",
    "- In quadrantChart, use this exact format:\n  quadrantChart\n    title ...\n  x-axis Low --> High\n  y-axis Low --> High\n  quadrant-1 Critical\n  quadrant-2 High\n  quadrant-3 Medium\n  quadrant-4 Low\n  Data_Point: [x, y]",
    "- Do NOT use %%{init:...}%% directives. They are deprecated and cause rendering failures.",
    "- Use only standard diagram types: flowchart, graph, sequenceDiagram, classDiagram, erDiagram, gantt, pie, gitGraph, quadrantChart.",
    "- In style and classDef lines, use only semantic class names. Do NOT use hardcoded hex colors (e.g. fill:#f9f).",
    "- Ensure every Mermaid codeblock starts with the diagram type keyword on the FIRST line after the opening fence.",
  ].join(" "),
  userPrompt: [
    "Generate CHAPTER 6: TESTING & QUALITY ASSURANCE (20 A4 pages)",
    "",
    "## 6.1 Testing Philosophy",
    "(2 pages) Al-Azhar University testing guidelines: Unit -> Integration -> E2E -> Manual pyramid.",
    "Reproducibility: Docker containers for all test environments.",
    "",
    "## 6.2 Unit Testing",
    "(5 pages) Backend: xUnit framework with >=90% statement coverage via coverlet.",
    "Frontend: Jest + Testing Library with >=85% statement coverage.",
    "Include Mermaid pie chart for backend coverage dashboard.",
    "Reference: Figure 6.2.b: Backend coverage dashboard.",
    "",
    "## 6.3 Integration Testing",
    "(5 pages) 3-Tier interactions: SQL -> .NET Core -> Next.js.",
    "Postman API test suite covering all API endpoints.",
    "",
    "## 6.4 End-to-End Testing",
    "(6 pages) Cypress test suites with comprehensive coverage table:",
    "| Suite ID | Suite Name | Runs | Pass Rate | Test Case Count |",
    "Include screenshots of Cypress runner for each major workflow.",
    "Reference: Figure 6.4.a: Cypress test runner dashboard.",
    "",
    "## 6.5 Testing Infrastructure",
    "(2 pages) Mermaid architecture diagram showing:",
    "KubernetesCluster -> StagingEnvironment, GitHubActions -> CypressTestRunner -> TestReport",
    "Reference: Figure 6.5: Testing infrastructure.",
    "",
    "## 6.6 Continuous Integration & Environment Reproducibility",
    "(3 pages) Reference Appendix A for CI/CD workflow details.",
    "",
    "ALL diagrams must be Mermaid inside codeblocks with Figure X.x references.",
    "Start with '# CHAPTER 6: TESTING & QUALITY ASSURANCE' as the top-level heading.",
  ].join("\n"),
};
